### ISSUE TITLE
Visual Recognition node crashes Node-RED when sent msg.params.detect_mode=text

### ISSUE THREAD

**Issue by johnwalicki** [watson-developer-cloud/node-red-node-watson#368] opened 2018-02-02 16:32 UTC
After node-red-node-watson 0.6.0 removed  the Text Recognition option from the Visual Recognition Node
any flow that tries to call it with params.detect_mode = text will crash the Node-RED runtime.

I send the Visual Recognition node this msg.params
params.detect_mode = text

2 Feb 11:26:00 - [error] [visual-recognition-v3:13454488.01f9c3] Invalid parameter setting for detect_mode, using configuration value
Segmentation fault

**Comment by chughts** [comment] 2018-02-04 15:37
I am unable to reproduce. I get:

`"Invalid parameter setting for detect_mode, using configuration value"`

If I force the configuration value to 'recognizeText' or something else Invalid I get:

```
"Invalid parameter setting for detect_mode, using configuration value"
"Mode recognizeText not understood"
```

but no segmentation fault in either case.
I have the latest version of the nodes -  0.6.2
node-red - 0.17.4

**Comment by chughts** [comment] 2018-05-06 13:49
Closing as URP

**Closed as completed by chughts** 2018-05-06 13:49 UTC
