### ISSUE TITLE
Document conversion destroys incoming msg context

### ISSUE THREAD

**Issue by rcruicks** [watson-developer-cloud/node-red-node-watson#217] opened 2016-11-14 14:07 UTC
most other nodes (have not checked all) take the approach of placing the Watson output in the payload of the incoming msg object - i.e. msg.payload = watson-response; node.send(msg); 

Document conversion overwrites current msg by using - node.send({"payload": watson-response});

this obliterates the original URL in the payload, and any other msg properties (_id, url, topic, etc);
makes it unnecessarily complicated to convert a document, and immediately store in cloudant or other repository, having set doc id and url to tag the doc in the database

**Comment by chughts** [comment] 2016-11-15 10:38
Then team are investigating will reply here.

**Comment by gibfahn** [comment] 2016-11-15 12:19
@rcruicks So to clarify, the issue is that the document conversion node [clears all the `msg.xxx` properties](https://github.com/watson-developer-cloud/node-red-node-watson/blob/master/services/document_conversion/v1.js#L83-L85) and returns a msg object containing only the `msg.payload`?

If we were to pass on the original msg object and simply change the `msg.payload` then that would work for you?

**Comment by rcruicks** [comment] 2016-11-15 12:39
@gibfahn hi Gibson - yes - from what I can see, all other Watson nodes take this approach, returning the Watson response in the payload of the original msg, or in a new msg property (msg.transcript, msg,speech, and the like)
general node-red node behaviour is to pass on the original msg; this is often needed for things like http-in request flows, which need msg.req to be able to respond through http-response

**Comment by chughts** [comment] 2016-11-28 20:12
Fixed in 0.4.29

**Closed as completed by chughts** 2016-11-28 20:12 UTC
